logging = "localRPC=info,gossipbus=info,utils=info,services=info,ethereum=info,main=warn,validator=info,monitor=info,deploy=info,consensus=info,peerMan=info,muxHandler=info,p2pmux=info,app=error,transport=error,dman=info,status=info,db=info,yamux=error,badger=error,monitor_bus=error"

[chain]
id = 42
stateDB = "~/validator2/"
stateDBInMemory = false
transactionDB = ""
transactionDBInMemory = true
monitorDB = ""
monitorDBInMemory = true

[bootnode]
listeningAddress = "0.0.0.0:4244"
cacheSize = 20

[transport]
originLimit = 50
privateKey = "cccccccccccccccccccccccccccccccc"
bootNodeAddresses = "0000002a|029570051a8573e865af31a066eb100e7744bcbd05d814e899a763500163675be9@127.0.0.1:4242"
p2pListeningAddress = "0.0.0.0:4345"
discoveryListeningAddress = "0.0.0.0:4446"
localStateListeningAddress = "0.0.0.0:8886"
peerLimitMax = 24
peerLimitMin = 1

[monitor]
batchSize = 1000
interval = "7s"

[ethereum]
defaultAccount = "0x63a6627b79813A7A43829490C4cE409254f64177"
endpoint = "http://localhost:8545"
endpointPeers = 0
keystore = "assets/test/keys"
timeout = "1h"
passcodes = "assets/test/passcodes.txt"
testEther = "f000000000000000000"
finalityDelay = 2
retryCount = 3
retryDelay = "5s"
startingBlock = 1
registryAddress = "0x0b1f9c2b7bed6db83295c7b5158e3806d67ec5bc"

[edge]
ethTimeout = "5s"

[utils]
status = true

[validator]
rewardAccount = "0x63a6627b79813A7A43829490C4cE409254f64177"
rewardCurveSpec = 1
symmetricKey = "someSuperFancySecretThatWillBeHashed"
