// Generated by ifacemaker. DO NOT EDIT.

package bindings

import (
	"math/big"

	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
)

// IBridgePoolDepositNotifierTransactor ...
type IBridgePoolDepositNotifierTransactor interface {
	// DoEmit is a paid mutator transaction binding the contract method 0xc58b0a4f.
	//
	// Solidity: function doEmit(bytes32 salt, address ercContract, uint256 number, address owner) returns()
	DoEmit(opts *bind.TransactOpts, salt [32]byte, ercContract common.Address, number *big.Int, owner common.Address) (*types.Transaction, error)
}
