run:
  timeout: 5m
  build-tags:
    - integration
    - flakes
linters:
  # Disabling linters until we get them fixed up.
  disable:
    - errcheck
    - deadcode
    - gosimple
    - ineffassign
    - staticcheck
    - unused
    - varcheck