logging = "gossipbus=debug,utils=debug,services=debug,ethereum=debug,main=debug,validator=debug,monitor=debug,deploy=debug,consensus=debug,peerMan=debug,muxHandler=debug,p2pmux=debug,app=debug"

[chain]
id = 1337

[bootnode]
listeningAddress = "0.0.0.0:4242"
cacheSize = 16

[transport]
originLimit = 10
privateKey = "7769e8f01f52bb964dee65c069e19bc54e525855995c82b84dd739013c0891a0"
