logging = "main=info,ethereum=info,consensus=debug"

[loglevel]
blockchain = "debug"
consensus = "debug"
admin = "debug"

[chain]
id = 67
stateDB = "./scripts/generated/stateDBs/integration/"
stateDBInMemory = false
transactionDB = ""
transactionDBInMemory = true
monitorDB = "scripts/generated/monitorDBs/integration/"
monitorDBInMemory = false

[bootnode]
listeningAddress = ""
cacheSize = 20

[transport]
upnp = false
originLimit = 50
privateKey = "0E6A7E40AC1C69C936DD03EAB9669651"
bootNodeAddresses = "0000002a|029570051a8573e865af31a066eb100e7744bcbd05d814e899a763500163675be9@127.0.0.1:4242"
p2pListeningAddress = "0.0.0.0:4343"
discoveryListeningAddress = "0.0.0.0:4445"
localStateListeningAddress = "0.0.0.0:8885"
peerLimitMax = 24
peerLimitMin = 3

[monitor]
batchSize = 1_000
interval = "7s"
timeout = "1h"

[ethereum]
defaultAccount = "0x546F99F244b7B58B855330AE0E2BC1b30b41302F"
endpoint = "http://localhost:8545"
endpointPeers = 0
keystore = ""
timeout = "1h"
passcodes = ""
testEther = "f000000000000000000"
finalityDelay = 6
retryCount = 10
retryDelay = "5s"
startingBlock = 1
registryAddress = "0x9bebADdd34730b83b1372e4ED1BD67e4f84A02C8"
txFeePercentageToIncrease = 50
txMaxFeeThresholdInGwei = 1000000
txCheckFrequency = "5s"
txTimeoutForReplacement = "30s"

[edge]
ethTimeout = "5s"

[utils]
status = true

[validator]
rewardAccount = "0x546F99F244b7B58B855330AE0E2BC1b30b41302F"
rewardCurveSpec = 1
symmetricKey = "someSuperFancySecretThatWillBeHashed"
