name: 'Configure node js and its cache'
description: 'Configure node js and its cache'
runs:
  using: "composite"
  steps:
  - uses: actions/setup-node@v3
    working-directory: ./bridge
    with:
      node-version: ${{ env.NODE_VERSION }}
      cache: 'npm'
