name: 'V1Artifacts'
description: 'caches v1 contract artifacts'
runs:
  using: "composite"
  steps:
  - uses: actions/cache@v3
    name: "V1Artifacts Cache"
    id: artifacts-cache
    with:
      path: '**/legacy/V1'
      key: ${{ runner.os }}-artifacts-${{ hashFiles('**/legacy/V1ArtifactsArchive.tar.gz') }}
  - if: steps.artifacts-cache.outputs.cache-hit != 'true'
    shell: bash
    run: make generate-bridge

    