name: 'Run the solidity unit tests in groups'
description: 'Run the solidity unit tests in groups'
inputs:
  test-group:
    description: 'Regex to math the folder inside the test folder'
    required: true
  sub-filter-include:
    description: 'Sub folder to include in the search'
    required: false
  sub-filter-exclude:
    description: 'Sub folder to exclude in the search'
    required: false
runs:
  using: "composite"

  steps:
  - name: "V1Artifacts Cache"
    id: artifacts-cache
    uses: actions/cache@v3
    with:
      path: '**/legacy/V1'
      key: ${{ runner.os }}-artifacts-${{ hashFiles('**/legacy/V1ArtifactsArchive.tar.gz') }}
  - if: steps.artifacts-cache.outputs.cache-hit != 'true'
    shell: bash
  
    run: make generate-bridge
  - shell: bash
    working-directory: ./bridge
    run: npm run clean && npm run compile
  - shell: bash
    working-directory: ./bridge
    run: |
      SUB_FILTER_INCLUDE=/${{ inputs.sub-filter-include }}
      # if inputs.sub-filter-include is empty we have to remove '/' if not
      # the find command bellow will fail
      if [[ "$SUB_FILTER_INCLUDE" == "/" ]];  then
        SUB_FILTER_INCLUDE=""
      fi
      ls ./test | \
      grep "^${{ inputs.test-group }}" | \
      xargs -n 1 -I {} echo ./test/{}$SUB_FILTER_INCLUDE | \
      xargs -n 1 -I {} find -P {} -type f -iname '*.ts' -not -path "*/${{ inputs.sub-filter-exclude }}/*" | \
      xargs npm run test-parallel --
