name: Alicenet CI

on:
  push:
    branches: [ main, candidate ]
    paths:
      - "blockchain"
  pull_request:
    branches: [ main, candidate ]

env:
  NODE_VERSION: 16.x

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  solidity-build:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./bridge
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node-cache
    
  solidity-unit-tests:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    strategy:
      matrix:
        include:
          - test-group: "[0-9a-dA-D]"
          - test-group: "[eE]"
            sub-filter-exclude: "ethdkg/phases"
          - test-group: "ethdkg"
            sub-filter-include: "phases"
            sub-filter-exclude: "accusations"
          - test-group: "ethdkg"
            sub-filter-include: "phases/accusations"
          - test-group: "[f-qF-Q]"
          - test-group: "[r-sR-S]"
          - test-group: "[t-zT-Z]"
    needs: solidity-build
    defaults:
      run:
        working-directory: ./bridge
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node-cache
      - uses: ./.github/actions/solidity-tests
        with:
          test-group: ${{ matrix.test-group }}
          sub-filter-include: ${{ matrix.sub-filter-include }}
          sub-filter-exclude: ${{ matrix.sub-filter-exclude }}
    
  solidity-linter:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    needs: solidity-build
    defaults:
      run:
        working-directory: ./bridge
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node-cache
      - run: npm run lint-solidity
    
  typescript-linter:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    needs: solidity-build
    defaults:
      run:
        working-directory: ./bridge
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node-cache
      - run: npm run clean && npm run compile && npm run typechain
      - run: npm run lint
  
  golang-build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    needs: solidity-build
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
    steps:
      - name: "Sanitize branch name"
        run: |
          echo "BRANCH_NAME=$(echo ${{ github.head_ref || github.ref_name }} | sed -E 's/[^[:alnum:]]+/_/g')" >> $GITHUB_ENV
          echo "OPERATING_SYSTEM=$(echo ${{ matrix.os }} | sed -E 's/[^[:alnum:]]+/_/g')" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - uses: ./.github/actions/alicenet-config
      - run: make build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: alicenet-${{ env.BRANCH_NAME }}-${{ env.OPERATING_SYSTEM }}
          path: ./madnet
    
  golang-vet:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    needs: golang-build
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/alicenet-config
      - run: go vet ./...
    
  golang-linter:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    needs: golang-build
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/alicenet-config
      - name: install-golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
      - name: run golangci-lint
        run: golangci-lint run ./...
  
  golang-unit-tests:
    runs-on: ${{ matrix.os }}
    needs: golang-build
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
    steps:
        # Checkout and tool to format the test output
      - uses: actions/checkout@v3
      - uses: ./.github/actions/alicenet-config
      - name: Set up gotestfmt
        run: go install github.com/haveyoudebuggedit/gotestfmt/v2/cmd/gotestfmt@latest
      - name: Run unit tests
        timeout-minutes: 20
        run: |
           set -euo pipefail
           go test -json -v $(go list ./... | grep -Ev '/blockchain') 2>&1 | tee /tmp/gotest.log | gotestfmt

  golang-blockchain-tests:
    runs-on: ${{ matrix.os }}
    needs: golang-build
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04 ]
        test-cmd: [
          github.com/MadBase/MadNet/blockchain/dkg/dkgtasks -run TestShareDistribution,
          github.com/MadBase/MadNet/blockchain/dkg/dkgtasks -run TestRegisterTask,
          github.com/MadBase/MadNet/blockchain/dkg/dkgtasks -run TestMPKSubmission,
          github.com/MadBase/MadNet/blockchain/dkg/dkgtasks -run TestKeyShareSubmission,
          github.com/MadBase/MadNet/blockchain/dkg/dkgtasks -run TestGPKjSubmission,
          github.com/MadBase/MadNet/blockchain/dkg/dkgtasks -run TestDisputeShareDistributionTask,
          github.com/MadBase/MadNet/blockchain/dkg/dkgtasks -run TestDisputeMissingShareDistributionTask,
          github.com/MadBase/MadNet/blockchain/dkg/dkgtasks -run TestDisputeMissingRegistrationTask,
          github.com/MadBase/MadNet/blockchain/dkg/dkgtasks -run TestDisputeMissingKeySharesTask,
          github.com/MadBase/MadNet/blockchain/dkg/dkgtasks -run TestDisputeMissingGPKjTask,
          github.com/MadBase/MadNet/blockchain/dkg/dkgtasks -run TestGPKjDispute,
          github.com/MadBase/MadNet/blockchain/dkg/dkgtasks -run TestCompletion,
          github.com/MadBase/MadNet/blockchain,
          github.com/MadBase/MadNet/blockchain/dkg,
          github.com/MadBase/MadNet/blockchain/dkg/math,
          github.com/MadBase/MadNet/blockchain/monitor,
          github.com/MadBase/MadNet/blockchain/objects,
          github.com/MadBase/MadNet/blockchain/tasks
        ]
    steps:
      # Checkout and tool to format the test output
      - uses: actions/checkout@v3
      - uses: ./.github/actions/alicenet-config
      - name: Set up gotestfmt
        run: go install github.com/haveyoudebuggedit/gotestfmt/v2/cmd/gotestfmt@latest
      
      # Install ubuntu eth and missing dependencies
      - name: Check out ethereum repo for ethkey
        uses: actions/checkout@master
        with:
          repository: ethereum/go-ethereum
          path: './go-ethereum'
      - name: Install geth and ethkey
        run: |
          REPO_PATH=$(pwd)
          cd go-ethereum
          sudo apt install make gcc
          make all
          cd  /usr/local/bin
          sudo ln -s $REPO_PATH/go-ethereum/build/bin/ethkey /usr/local/bin
          cd $REPO_PATH
          sudo add-apt-repository -y ppa:ethereum/ethereum
          sudo apt-get update
          sudo apt-get install -y ethereum
      
      # Run matrix blockchain unit tests
      - name: Run tests ${{ matrix.test-cmd }}
        timeout-minutes: 45
        run: |
          set -euo pipefail
          ./scripts/main.sh init 5
          go test -v -timeout=45m ${{ matrix.test-cmd }}
