name: Alicenet CI

on:
  workflow_dispatch:
  push:
    branches: [ main, candidate ]
  pull_request:
    branches: [ main, candidate ]

env:
  NODE_VERSION: 16.x

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  solidity-build:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./bridge
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node-cache
      - uses: ./.github/actions/artifacts-cache
    
  solidity-unit-tests:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    strategy:
      matrix:
        include:
          - test-group: "[0-9a-dA-D]"
          - test-group: "[eE]"
            sub-filter-exclude: "ethdkg/phases"
          - test-group: "ethdkg"
            sub-filter-include: "phases"
            sub-filter-exclude: "accusations"
          - test-group: "ethdkg"
            sub-filter-include: "phases/accusations"
          - test-group: "[f-qF-Q]"
          - test-group: "[r-sR-S]"
          - test-group: "[t-zT-Z]"
    needs: solidity-build
    defaults:
      run:
        working-directory: ./bridge
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node-cache
      - uses: ./.github/actions/artifacts-cache
      - run : tar -xvf legacy/V1ArtifactsArchive.tar.gz --directory legacy
      - uses: ./.github/actions/solidity-tests
        with:
          test-group: ${{ matrix.test-group }}
          sub-filter-include: ${{ matrix.sub-filter-include }}
          sub-filter-exclude: ${{ matrix.sub-filter-exclude }}
    
  solidity-linter:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    needs: solidity-build
    defaults:
      run:
        working-directory: ./bridge
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node-cache
      - run: npm run lint-solidity
    
  typescript-linter:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    needs: solidity-build
    defaults:
      run:
        working-directory: ./bridge
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node-cache
      - run: npm run clean && npm run compile && npm run typechain
      - run: npm run lint
  
  golang-build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    needs: solidity-build
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
    steps:
      - name: "Sanitize branch name"
        run: |
          echo "BRANCH_NAME=$(echo ${{ github.head_ref || github.ref_name }} | sed -E 's/[^[:alnum:]]+/_/g')" >> $GITHUB_ENV
          echo "OPERATING_SYSTEM=$(echo ${{ matrix.os }} | sed -E 's/[^[:alnum:]]+/_/g')" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - uses: ./.github/actions/alicenet-config
      - run: make build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: alicenet-${{ env.BRANCH_NAME }}-${{ env.OPERATING_SYSTEM }}
          path: ./madnet
    
  golang-linter:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    needs: golang-build
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/alicenet-config
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
  
  golang-unit-tests:
    runs-on: ${{ matrix.os }}
    needs: golang-build
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/alicenet-config
      - name: Set up gotestfmt
        run: go install github.com/haveyoudebuggedit/gotestfmt/v2/cmd/gotestfmt@latest
      - name: Run unit tests
        timeout-minutes: 20
        run: |
          set -euo pipefail
          go test -json -v -covermode=atomic -coverprofile=coverage.out ./... 2>&1 | tee /tmp/gotest.log | gotestfmt
      - name: Run unit tests (race detection)
        timeout-minutes: 20
        run: |
          set -euo pipefail
          go test -race -json -v -covermode=atomic -coverprofile=coverage.out ./... 2>&1 | tee /tmp/gotest.log | gotestfmt
      - uses: codecov/codecov-action@v1
        with:
          files: ./coverage.out
          verbose: true

  golang-blockchain-tests:
    runs-on: ${{ matrix.os }}
    needs: golang-build
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04 ]
        test-cmd: [
          github.com/MadBase/MadNet/blockchain/dkg/dkgtasks -run TestShareDistribution_Group_1,
          github.com/MadBase/MadNet/blockchain/dkg/dkgtasks -run TestShareDistribution_Group_2,
          github.com/MadBase/MadNet/blockchain/dkg/dkgtasks -run TestShareDistribution_Group_3,
          github.com/MadBase/MadNet/blockchain/dkg/dkgtasks -run TestRegisterTask_Group_1,
          github.com/MadBase/MadNet/blockchain/dkg/dkgtasks -run TestRegisterTask_Group_2,
          github.com/MadBase/MadNet/blockchain/dkg/dkgtasks -run TestRegisterTask_Group_3,
          github.com/MadBase/MadNet/blockchain/dkg/dkgtasks -run TestMPKSubmission_Group_1,
          github.com/MadBase/MadNet/blockchain/dkg/dkgtasks -run TestMPKSubmission_Group_2,
          github.com/MadBase/MadNet/blockchain/dkg/dkgtasks -run TestKeyShareSubmission,
          github.com/MadBase/MadNet/blockchain/dkg/dkgtasks -run TestGPKjSubmission_Group_1,
          github.com/MadBase/MadNet/blockchain/dkg/dkgtasks -run TestGPKjSubmission_Group_2,
          github.com/MadBase/MadNet/blockchain/dkg/dkgtasks -run TestDisputeShareDistributionTask_Group_1,
          github.com/MadBase/MadNet/blockchain/dkg/dkgtasks -run TestDisputeShareDistributionTask_Group_2,
          github.com/MadBase/MadNet/blockchain/dkg/dkgtasks -run TestDisputeMissingShareDistributionTask_Group_1,
          github.com/MadBase/MadNet/blockchain/dkg/dkgtasks -run TestDisputeMissingShareDistributionTask_Group_2,
          github.com/MadBase/MadNet/blockchain/dkg/dkgtasks -run TestDisputeMissingRegistrationTask_Group_1,
          github.com/MadBase/MadNet/blockchain/dkg/dkgtasks -run TestDisputeMissingRegistrationTask_Group_2,
          github.com/MadBase/MadNet/blockchain/dkg/dkgtasks -run TestDisputeMissingKeySharesTask,
          github.com/MadBase/MadNet/blockchain/dkg/dkgtasks -run TestDisputeMissingGPKjTask_Group_1,
          github.com/MadBase/MadNet/blockchain/dkg/dkgtasks -run TestDisputeMissingGPKjTask_Group_2,
          github.com/MadBase/MadNet/blockchain/dkg/dkgtasks -run TestGPKjDispute,
          github.com/MadBase/MadNet/blockchain/dkg/dkgtasks -run TestCompletion_Group_1,
          github.com/MadBase/MadNet/blockchain/dkg/dkgtasks -run TestCompletion_Group_2,
          github.com/MadBase/MadNet/blockchain/dkg/dkgtasks -run TestCompletion_Group_3,
          github.com/MadBase/MadNet/blockchain,
          github.com/MadBase/MadNet/blockchain/dkg,
          github.com/MadBase/MadNet/blockchain/dkg/math,
          github.com/MadBase/MadNet/blockchain/monitor,
          github.com/MadBase/MadNet/blockchain/objects,
          github.com/MadBase/MadNet/blockchain/tasks
        ]
    steps:
      # Checkout and tool to format the test output
      - uses: actions/checkout@v3
      - uses: ./.github/actions/alicenet-config
      - name: Set up gotestfmt
        run: go install github.com/haveyoudebuggedit/gotestfmt/v2/cmd/gotestfmt@latest

      # Run matrix blockchain unit tests
      - name: Run tests ${{ matrix.test-cmd }}
        timeout-minutes: 45
        run: |
          set -euo pipefail
          ./scripts/main.sh init 5
          go test -tags=integration -json -v -timeout=15m ${{ matrix.test-cmd }} 2>&1 | tee /tmp/gotest.log | gotestfmt
